export const styles = [
  'cyberpunk',
  '3d illustration',
  'minimal',
  'glassmorphism',
  'neon',
  'dark tech',
  'futuristic',
  'anime tech',
  'startup workspace',
  'modern ui ux',
  'retro futuristic',
  'cinematic',
  'digital painting',
  'isometric',
  'photorealistic',
  'sci fi',
  'abstract tech',
  'holographic',
]

export const scenes = [
  'developer desk setup',
  'AI coding workspace',
  'programmer using multiple monitors',
  'modern software company office',
  'full stack developer environment',
  'react developer workstation',
  'next js futuristic dashboard',
  'backend server room',
  'cloud computing illustration',
  'javascript coding scene',
  'typescript developer setup',
  'modern programming workspace',
  'startup engineering team',
  'AI robot coding',
  'future internet technology',
]

export const moods = [
  'cinematic lighting',
  'dramatic lighting',
  'dark mode aesthetic',
  'vibrant colors',
  'ultra detailed',
  'high contrast',
  'modern aesthetic',
  'professional lighting',
  'creative atmosphere',
  'soft ambient lighting',
]

export const cameraAngles = [
  'top view',
  'side angle',
  'isometric angle',
  'cinematic close up',
  'wide shot',
  'drone perspective',
  'front angle',
  'macro shot',
  'low angle',
  'high angle',
  'over the shoulder shot',
  'first person perspective',
  'fish eye lens',
  'ultra wide angle',
  'close portrait shot',
  'cinematic depth of field',
  'tilted angle',
  'aerial view',
  'panoramic shot',
  'zoomed in detail shot',
]

export const colorThemes = [
  'blue neon',
  'purple cyberpunk',
  'orange futuristic',
  'green matrix',
  'dark monochrome',
  'sunset gradient',
  'glass neon',
  'pastel futuristic',
  'electric blue',
  'pink vaporwave',
  'golden glow',
  'dark purple aesthetic',
  'red cyberpunk',
  'silver chrome',
  'white minimal',
  'black and gold',
  'holographic rainbow',
  'teal futuristic',
  'deep space colors',
  'midnight neon',
]

export const environments = [
  'rainy cyber city',
  'space station',
  'startup office',
  'futuristic server room',
  'modern tech lab',
  'dark coding room',
  'minimal workspace',
  'AI laboratory',
  'underground hacker room',
  'modern silicon valley office',
  'futuristic classroom',
  'robotics workshop',
  'gaming setup room',
  'high tech apartment',
  'virtual reality world',
  'digital metaverse city',
  'luxury coding setup',
  'moon base control room',
  'sci fi engineering bay',
  'floating futuristic island',
]
